# Common values
generic-service:
  productId: HMPPS518
  nameOverride: manage-people-on-probation-and-delius

  image:
    repository: ghcr.io/ministryofjustice/hmpps-probation-integration-services/manage-people-on-probation-and-delius

  ingress:
    tlsSecretName: manage-people-on-probation-and-delius-cert

  namespace_secrets:
    common:
      SPRING_DATASOURCE_URL: DB_URL
    manage-people-on-probation-and-delius-client-credentials:
      OAUTH2_CLIENT-ID: CLIENT_ID
      OAUTH2_CLIENT-SECRET: CLIENT_SECRET
    manage-people-on-probation-and-delius-database:
      SPRING_DATASOURCE_USERNAME: DB_USERNAME
      SPRING_DATASOURCE_PASSWORD: DB_PASSWORD
    manage-people-on-probation-and-delius-sentry:
      SENTRY_DSN: SENTRY_DSN

generic-prometheus-alerts:
  targetApplication: manage-people-on-probation-and-delius

