name: Get build info
description: Generate build info files for Gradle projects

inputs:
  project:
    description: The name of the project
    required: true
  version:
    description: The version of the service to deploy
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Get build info
      run: |
        echo '::group::Generate build info'
        ./gradlew "${PROJECT}:buildInfo" "${PROJECT}:gitInfo"
        sed -i "s/build.version=.*/build.version=$VERSION/" "projects/${PROJECT}/build-info.properties"
        echo '::endgroup::'
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        PROJECT: ${{ inputs.project }}

    - name: Store build info
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: build-info-${{ inputs.project }}
        path: projects/${{ inputs.project }}/build-info.properties

    - name: Store git info
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: git-info-${{ inputs.project }}
        path: projects/${{ inputs.project }}/git.properties
