name: Render project template
description: Renders a project template from the templates/projects directory and adds it to the Gradle build

inputs:
  issue_number:
    description: Issue number (e.g. PI-123)
    required: true
  project_name:
    description: Project name
    required: true
  environment:
    description: Namespace suffix e.g. dev
    required: true
  app-client-id:
    description: App ID
    required: true
  app-private-key:
    description: App private key
    required: true
outputs:
  pull-request-url:
    description: URL of the pull request created
    value: ${{ steps.pr.outputs.pull-request-url }}

runs:
  using: composite
  steps:
    - id: project_name
      shell: bash # language=bash
      run: echo "hash=$(echo -n $project_name | sha1sum | head -c 8)" | tee -a "$GITHUB_OUTPUT"
      env:
        project_name: ${{ inputs.project_name }}

    - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      id: app-token
      with:
        owner: ministryofjustice
        repositories: cloud-platform-environments
        client-id: ${{ inputs.app-client-id }}
        private-key: ${{ inputs.app-private-key }}

    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        repository: ministryofjustice/cloud-platform-environments
        token: ${{ steps.app-token.outputs.token }}

    - name: Add Pingdom check
      shell: bash # language=bash
      if: inputs.environment == 'prod'
      run: sed -i '/add new projects here/i \    "'$project_name'",' 'namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-prod/resources/pingdom.tf'
      env:
        project_name: ${{ inputs.project_name }}

    - name: Render certificate templates
      shell: bash # language=bash
      run: |
        sed 's/$SERVICE_NAME/'"${project_name}"'/g;
             s/$SERVICE_URL/'"${project_name}-${environment}"'.hmpps.service.justice.gov.uk/g;
             s/$SERVICE_SHORT_URL/'"${project_name_hash}-${environment}"'.hmpps.service.justice.gov.uk/g;
             s/$ENV/'"${environment}"'/g' \
          "${GITHUB_ACTION_PATH}/../../../templates/certificate.yml" >> "namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-$environment/05-certificates.yml"
      env:
        project_name: ${{ inputs.project_name }}
        project_name_hash: ${{ steps.project_name.outputs.hash }}
        environment: ${{ inputs.environment }}

    - name: Create pull request
      id: pr
      uses: ministryofjustice/hmpps-probation-integration-services/.github/actions/create-signed-pull-request@fix-bootstrap-token-2
      with:
        add-paths: namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-${{ inputs.environment }}
        branch: ${{ inputs.issue_number }}-create-${{ inputs.project_name }}-infra-${{ inputs.environment }}
        commit-message: ${{ inputs.issue_number }} Create certificate for ${{ inputs.project_name }} (${{ inputs.environment }})
        token: ${{ steps.app-token.outputs.token }}
        labels: bootstrap
