
style { ...@../../../../script/style.style }
vars { ...@../../../../script/style.vars }
** { ...@../../../../script/style.all-style }

Context-soc: SOC Context {
  entities: Entities {
    grid-columns: 3
    conviction: Conviction
    offence: Offence
    sentence: Sentence
    custody: Custody
    appearance: Court appearance
    detail: Detail
    area: Probation area
    ldu: Local delivery unit
    user: User
    pm: Person manager
    provider: Provider
    team: Team
    profile: Profile
    alias: Alias
  }
}

context-delius: Delius Context {

  interface: SOC\n and Delius {
    type: Anti-Corruption\nLayer
  }

  entities: Entities {
    grid-columns: 3
    pop: Person on Probation
    pm: Person manager
    staff: Staff
    team: Team
    area: Probation area
    district: District
    borough: Borough
    alias: Alias
    event: Event
    disposal: Disposal
    offence: Offence
    appearance: Court appearance
    court: Court
    release: Release
    nsi: NSI
    institution: Institution
    recall: Recall
  }
}

Context-soc--context-delius.interface: Upstream\n\n\nDownstream
