database:
  access:
    username_key: /cosso-and-delius/db-username
    password_key: /cosso-and-delius/db-password
    tables:
      - audited_interaction
      - document
      - address_assessment
      - assessment
      - contact
      - nsi
      - referral
      - registration
      - upw_appointment

  audit:
    username: CossoAndDelius
    forename: Breach Notice COSSO
    surname: Service
