generic-service:
  ingress:
    host: core-person-record-and-delius.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: prod
    INTEGRATIONS_CORE-PERSON-RECORD_URL: https://hmpps-person-record.hmpps.service.justice.gov.uk
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://sign-in.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://sign-in.hmpps.service.justice.gov.uk/auth/issuer
    MESSAGING_CONSUMER_DETAIL_URLS: https://hmpps-person-record.hmpps.service.justice.gov.uk
