
style { ...@common/style.style }
vars { ...@common/style.vars }
** { ...@common/style.all-style }

context-delius: Delius Context {

  entities: Entities {
    grid-columns: 2
    person: Person on Probation
    event: Domain event {
      message: Message body
      attributes: Message attributes
    }
  }
}

context-notification: Notification Context {

  interface: Delius and\n Notification {
    type: Anti-Corruption\nLayer
  }

  entities: Entities {
    grid-columns: 2
    notification: Notification {
      message: Message
      attributes: Attributes
    }
  }
}

context-delius--context-notification.interface: Upstream\n\n\nDownstream
