
style { ...@common/style.style }
vars { ...@common/style.vars }
** { ...@common/style.all-style }

context-opd: OPD Context {
  entities: Entities {
    grid-columns: 3
    pop: Person on Probation
    Assessment: OPD assessment
    result: OPD result
  }
}

context-delius: Delius Context {

  interface: OPD\n and Delius {
    type: Anti-Corruption\nLayer
  }

  entities: Entities {
    grid-columns: 2
    contact: Contact
    event: Event
    person: Person on Probation
    peron-manager: Person manager
    nsi-manager: NSI manager
    nsi: NSI
  }
}

context-opd--context-delius.interface: Upstream\n\n\nDownstream
