database:
  access:
    username_key: /community-support-interventions-and-delius/db-username
    password_key: /community-support-interventions-and-delius/db-password

  audit:
    username: CommunitySupportInterventionsAndDelius
    forename: Probation Integration Community Support Interventions
    surname: Service
