# Refer and Monitor Workflow: Delius Action Plan Changes

direction: right

style { ...@../../../../script/style.style }
vars { ...@../../../../script/style.vars }
** { ...@../../../../script/style.all-style }

# What triggers the workflow?
refer_and_monitor: Refer and Monitor  {
     style.font-size: 15
     crs_action_plan_submit: Submit\nAction Plan
     crs_action_plan_approve: Approve\nAction Plan
}

# What happens in Delius?
delius: Delius {
    style {
        font-size: 20
    }

    d_create_contact: Create\nAction Plan Contact
}

refer_and_monitor -> delius
