
style { ...@../../../../script/style.style }
vars { ...@../../../../script/style.vars }
** { ...@../../../../script/style.all-style }

context-refer-and-monitor: Refer and Monitor Context {
  link: https://github.com/ministryofjustice/hmpps-interventions-service

  entities: Entities {
    grid-columns: 3
    pop: Person\non Probation
    initial_appointment: CRS\nInitial Appointment
    delivery_session: CRS\nDelivery Session
  }
}

context-delius: Delius Context {
  style.stroke-width: 8

interface: Refer and Monitor and Delius {
    type: Anti-Corruption\nLayer
  }

  entities: Entities {
    grid-columns: 2
    pop: Person\non Probation { link: "https://ministryofjustice.github.io/hmpps-probation-integration-services/tech-docs/concepts.html#person" }
    nsi: NSI { link: "https://ministryofjustice.github.io/hmpps-probation-integration-services/tech-docs/concepts.html#non-statutory-intervention-nsi" }
    contacts: Appointment\nContacts { link: "https://ministryofjustice.github.io/hmpps-probation-integration-services/tech-docs/concepts.html#contact" }
    offices: Probation Offices
  }
}

context-refer-and-monitor--context-delius.interface: Upstream\n\n\nDownstream
