# Refer and Monitor Workflow: End CRS Referral

direction: right

style { ...@../../../../script/style.style }
vars { ...@../../../../script/style.vars }
** { ...@../../../../script/style.all-style }

# What triggers the workflow?
refer_and_monitor: Refer and Monitor  {
     style.font-size: 15
     crs_referral: End CRS referral
}

# What happens in Delius?
delius: Delius {
    style {
        font-size: 20
    }

    d_end_nsi: End referral NSI
    d_withdraw_appointments: Withdraw future\nDelius appointments
    d_create_contact: Create CRS referral\ntermination contacts
    d_add_eosr: Update\n'End of Service Report'\ncontact

    d_end_nsi -> d_withdraw_appointments -> d_create_contact -> d_add_eosr
}

refer_and_monitor -> delius
