# Refer and Monitor Workflow: Create Delius NSI

direction: right

style { ...@../../../../script/style.style }
vars { ...@../../../../script/style.vars }
** { ...@../../../../script/style.all-style }

# What triggers the workflow?
refer_and_monitor: Refer and Monitor  {
     style.font-size: 15
     crs_referral: Create CRS referral
}

# What happens in Delius?
delius: Delius {
    style {
        font-size: 20
    }

    d_create_nsi: Create CRS\nreferral NSI
    d_create_contact: Create CRS\nreferral contacts

    d_create_nsi -> d_create_contact
}

refer_and_monitor -> delius
