# CAS2 Workflow: Referral Application Status Update

style { ...@../../../../script/style.style }
vars { ...@../../../../script/style.vars }
** { ...@../../../../script/style.all-style }

direction: right

# What triggers the workflow?
cas2: CAS2  {
     style.font-size: 24

     explanation: |md
     ## Referral Application Workflow
     Updates to referral applications raise domain events
     |

     application_updated: Application Updated
}

domain_event_1: "applications.cas2\n.application.status-updated" {
    style.font-size: 12
    shape: queue
}

# What happens in Delius?
delius: Delius {
    style.font-size: 24

     explanation: |md
     ## Delius Workflow
     Referral application status contact is created\
     or updated Delius to reflect referral application changes
     |

    d_contact_create: Create Contact
    d_contact_update: Update Contact
}

cas2 -> domain_event_1

domain_event_1 -> delius
