
style { ...@../../../../script/style.style }
vars { ...@../../../../script/style.vars }
** { ...@../../../../script/style.all-style }

context-sar: Subject Access Requests Context {
  entities: Entities {
    grid-columns: 1
    name: Name
    user: User
  }
}

context-delius: Delius Context {

  interface: SAR\n and Delius {
    type: Anti-Corruption\nLayer
  }

  entities: Entities {
    grid-columns: 1
    pop: Person on probation
    user: User
  }
}

context-sar--context-delius.interface: Upstream\n\n\nDownstream
