style {
  fill: "#ffffff"
  stroke: "#000000"
  stroke-width: 2
}

all-style {
  style {
    border-radius: 10
    stroke-width: 2
  }
}

vars: {
  d2-config: {
    pad: 25
    center: true
    layout-engine: elk
    theme-id: 8
  }
}
