
style { ...@../../../../script/style.style }
vars { ...@../../../../script/style.vars }
** { ...@../../../../script/style.all-style }

context-cp: Common Platform Context {
  entities: Entities {
    grid-columns: 3
    hearing: Hearing
    case: Prosecution case
    defendant: Defendant
    offence: Hearing offence
    result: Judicial result
    plea: Plea
    verdict: Verdict
    person: Person details
    address: Address
    court: Court centre
    day: Hearing day
  }
}

context-delius: Delius Context {

  interface: Common Platform\n and Delius {
    type: Anti-Corruption\nLayer
  }

  entities: Entities {
    grid-columns: 3
    contact: Contact
    event: Event
    appearance: Court appearance
    equality: Equality
    om: Order manager
    transfer: Transfer reason
    offence: Offence
    person: Person
    address: Person address
    pm: Person manager
    staff: Staff
    team: Team
  }
}

context-cp--context-delius.interface: Upstream\n\n\nDownstream
