# Manage POM Cases Workflow: Update Delius POM Responsibility

direction: right

style {
  fill: "#ffffff"
}

# What triggers the workflow?
mpc: Manage POM Cases {
     style.font-size: 15
     mpc_responsibility: POM responsibility\nupdated {
         shape: oval
     }
}

# What happens in Delius?
delius: Delius {
    style {
        font-size: 20
    }
    d_allocate_pom: Update allocated POM
    d_allocation_reason: Set POM allocation reason

    d_allocate_pom -> d_allocation_reason
}

mpc -> delius

*.style.border-radius: 10
*.*.style.border-radius: 10
*.*.style.stroke-width: 2
*.*.style.font-size: 12
