# Manage POM Cases Workflow: Update Delius POM to COM Handover Dates

direction: right

style { ...@../../../../script/style.style }
vars { ...@../../../../script/style.vars }
** { ...@../../../../script/style.all-style }

# What triggers the workflow?
mpc: Manage POM Cases {
     style.font-size: 15
     mpc_responsibility: POM to COM handover\ndates updated
}

# What happens in Delius?
delius: Delius {
    style {
        font-size: 20
    }
    d_key_dates: Update key dates
}

mpc -> delius
