
style {
  fill: "#ffffff"
}

context-approved-premises: Approved Premises Context {
  link: https://github.com/ministryofjustice/hmpps-approved-premises-api

  entities: Entities {
    grid-columns: 3
    referral: Approved Premises\n Referral
    application: Approved Premises\n Application
    booking: Approved Premises\n Booking
  }
}

context-delius: Delius Context {
  style.stroke-width: 8

  entities: Entities {
    grid-columns: 3
    pop: Person on Probation
    identifiers: Person Identifiers
    staff: Staff
    team: Team
    offender-manager: Offender Manager
    lao: Limited Access\ Offender
    contact: Contact
    referral: Approved Premises\n Referral
    documents: Probation Documents
  }
  interface: Approved Premises and Delius {
    type: Anti-Corruption Layer
  }
}

context-approved-premises--context-delius.interface: Upstream\n\n\nDownstream

*.style.border-radius: 10
*.*.style.border-radius: 10
*.*.style.stroke-width: 2
