# Approved Premises Workflow: Booking Made

direction: right

style {
  fill: "#ffffff"
}

# What triggers the workflow?
approved_premises: Approved Premises (CAS1)  {
     style.font-size: 24

     explanation: |md
     ## Booking Workflow
     Complete an Approved Premises Booking
     |

     booking_made: Complete Booking
}

domain_event: "approved-premises\n.booking.made" {
    style.font-size: 12
    shape: queue
}

# What happens in Delius?
delius: Delius {
    style.font-size: 24

     explanation: |md
     ## AP Referral Workflow
     Initiate Delius AP referral
     |

    d_referral: Create Delius\nAP Referral
    d_contact: Create Contact

    d_referral -> d_contact
}

approved_premises -> domain_event -> delius

*.style.border-radius: 10
*.*.style.border-radius: 10
*.*.style.stroke-width: 2
*.*.style.font-size: 12
