name: Check for changes
description: Check which projects have changed since branching from main

inputs:
  filters:
    description: Path patterns to use for matching changes
    default: |
      commons:
        - '*'
        - '.github/**'
        - 'templates/**'
        - 'buildSrc/**'
        - 'gradle/**'
        - 'libs/**'
      projects:
        - 'projects/**'

outputs:
  projects:
    description: A JSON array of projects that have changed
    value: ${{ steps.check-changes.outputs.projects }}

runs:
  using: "composite"
  steps:
    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      id: paths-filter
      with:
        base: main
        list-files: shell
        filters: ${{ inputs.filters }}
    - name: Check for changes
      id: check-changes
      env:
        COMMONS_CHANGED: ${{ steps.paths-filter.outputs.commons }}
        PROJECT_FILES: ${{ steps.paths-filter.outputs.projects_files }}
      shell: bash # language=bash
      run: |
        function toJsonArray() {
          jq --raw-input . | jq --slurp --compact-output .
        }
        
        function topLevelChanges() {
          sed -E 's|^projects/([^/$]*).*|\1|' | sort -u
        }
        
        if [ "$COMMONS_CHANGED" == "true" ]; then
          projects=$(find projects -mindepth 1 -maxdepth 1 -printf "%f\n" | toJsonArray)
          echo "Changes detected in common files, rebuild/deploy everything"
          echo "projects=$projects" | tee -a "$GITHUB_OUTPUT"
        elif [ -n "$PROJECT_FILES" ]; then
          projects=$(echo "$PROJECT_FILES" | xargs -n1 | topLevelChanges | toJsonArray)
          echo "Changes detected in: $projects"
          echo "projects=$projects" | tee -a "$GITHUB_OUTPUT"
        else
          echo "No changes detected"
          echo "projects=[]" | tee -a "$GITHUB_OUTPUT"
        fi
