package uk.gov.justice.digital.hmpps.integrations.oasys.model

import java.time.ZonedDateTime

data class OasysHealthDetails(
    val limitedAccessOffender: Boolean,
    val assessments: List<OasysHealthAssessment>,
)

data class OasysHealthAssessment(
    override val assessmentPk: Long,
    override val assessmentType: String,
    override val dateCompleted: ZonedDateTime? = null,
    override val assessorSignedDate: ZonedDateTime? = null,
    override val initiationDate: ZonedDateTime,
    override val assessmentStatus: String,
    override val superStatus: String? = null,
    override val laterWIPAssessmentExists: Boolean? = null,
    override val lastUpdatedDate: ZonedDateTime? = null,
    val generalHealth: String? = null,
    val alcoholProgramme: String? = null,
    val alcoholEM: String? = null,
    val alcoholCommunity: String? = null,
    val interpreterProgramme: String? = null,
    val interpreterEM: String? = null,
    val interpreterCommunity: String? = null,
    val communicationProgramme: String? = null,
    val communicationEM: String? = null,
    val communicationCommunity: String? = null,
    val literacyProgramme: String? = null,
    val literacyEM: String? = null,
    val literacyCommunity: String? = null,
    val learningProgramme: String? = null,
    val learningEM: String? = null,
    val learningCommunity: String? = null,
    val motivationProgramme: String? = null,
    val motivationEM: String? = null,
    val motivationCommunity: String? = null,
    val psychiatricProgramme: String? = null,
    val psychiatricEM: String? = null,
    val psychiatricCommunity: String? = null,
    val disabilityProgramme: String? = null,
    val disabilityEM: String? = null,
    val disabilityCommunity: String? = null,
    val childCareProgramme: String? = null,
    val childCareEM: String? = null,
    val childCareCommunity: String? = null,
    val educationProgramme: String? = null,
    val educationEM: String? = null,
    val educationCommunity: String? = null,
    val employmentProgramme: String? = null,
    val employmentEM: String? = null,
    val employmentCommunity: String? = null,
    val transportProgramme: String? = null,
    val transportEM: String? = null,
    val transportCommunity: String? = null,
    val religiousProgramme: String? = null,
    val religiousEM: String? = null,
    val religiousCommunity: String? = null,
    val lifestyleProgramme: String? = null,
    val lifestyleEM: String? = null,
    val lifestyleCommunity: String? = null,
    val drugsProgramme: String? = null,
    val drugsEM: String? = null,
    val drugsCommunity: String? = null,
    val healthProgramme: String? = null,
    val healthEM: String? = null,
    val healthCommunity: String? = null,
    val elecMonSpecify: String? = null,
    val elecMonElectricity: String? = null,
    val elecMon: String? = null,
    val generalHeathSpecify: String? = null,
) : OasysAssessment()
