package uk.gov.justice.digital.hmpps.service

object ContractTypeNsiType {
    val MAPPING = mapOf(
        "ACC" to "CRS01",
        "ETE" to "CRS02",
        "PWB" to "CRS05",
        "WOS" to "CRS06",
        "DNR" to "CRS04",
        "MTR" to "CRS03",
        "WSM" to "CRS07",
        "FBD-B" to "CRS08",
        "FBD-BU" to "CRS08",
        "FBD-EM" to "CRS08",
        "FBD-M" to "CRS08",
        "FBD-R" to "CRS08",
        "FBD-WM" to "CRS08",
        "FBD-L" to "CRS08",
        "FBD-SA" to "CRS08",
        "FBD-SC" to "CRS08",
        "FBD-SP" to "CRS08",
        "FBD-NE" to "CRS08",
        "FBD-SW" to "CRS08",
        "FBD-TA" to "CRS08",
        "FBD-TR" to "CRS08",
        "FBD-W" to "CRS08",
        "FBD-WI" to "CRS08",
        "FBD-Y" to "CRS08",
        "FBD-NW" to "CRS08",
        "DNR-K" to "CRS04",
        "DNR-L" to "CRS04",
        "DNR-NE" to "CRS04",
        "DNR-Y" to "CRS04",
        "DNR-NEN" to "CRS04",
        "DNR-SC" to "CRS04",
        "DNR-SY" to "CRS04",
        "DNR-WM" to "CRS04",
        "DNR-SW" to "CRS04",
    )
}
