name: Analyse
description: Publish test results to GitHub Actions, and analyse source code and results using Sonar

inputs:
  sonar-token:
    description: Sonar token
    required: true
  gradle-cache-role:
    description: Role required for accessing Gradle cache
    required: true
  gradle-cache-encryption-key:
    description: Gradle cache encryption key. Required for configuration caching.
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        pattern: test-results-*
        path: test-results

    - name: Unpack test results
      run: for dir in test-results/*; do cp -R "$dir"/* .; done
      shell: bash

    - name: Publish unit test reports
      uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
      if: always() && github.actor != 'dependabot[bot]'
      with:
        name: Unit test results
        path: '**/build/test-results/test/TEST-*.xml'
        reporter: java-junit
        only-summary: true

    - name: Publish integration test reports
      uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
      if: always() && github.actor != 'dependabot[bot]'
      with:
        name: Integration test results
        path: '**/build/test-results/integrationTest/TEST-*.xml'
        reporter: java-junit
        only-summary: true

    - name: Set version
      id: version
      shell: bash
      run: |
        version=$(date '+%Y-%m-%d').${{ github.run_number }}.$(echo ${{ github.sha }} | cut -c1-7)
        echo "VERSION=$version" | tee -a "$GITHUB_ENV"
        echo "version=$version" | tee -a "$GITHUB_OUTPUT"

    - uses: ./.github/actions/setup-gradle
      with:
        cache-role: ${{ inputs.gradle-cache-role }}
        cache-encryption-key: ${{ inputs.gradle-cache-encryption-key }}

    - name: Sonar analysis
      if: github.actor != 'dependabot[bot]'
      run: ./gradlew sonar -Dsonar.projectVersion="$VERSION" --no-configuration-cache --no-parallel
      shell: bash
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
