# Domain Event Workflow: Domain Event Enhancement

direction: right

style { ...@../../../../script/style.style }
vars { ...@../../../../script/style.vars }
** { ...@../../../../script/style.all-style }

# Domain Event Enhancement
domain-event-enhancement: Domain Event Enhancement {
    style.font-size: 24
    grid-columns: 2

    d_get_events: Get domain events batch
    d_enhance_events: Enhance domain event
    d_publish: Publish notification

    d_get_events -> d_enhance_events -> d_publish

    explanation: |md
    ## Enhance an event
    - Get batch of domain events
    - If event type is supported,\
      enhance the event
    - Transform the event to\
      a notification
    - Publish the notification
    |

}
