#!/bin/bash

# Run from the base directory
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

# Create SVGs for all d2 diagrams
for d2_file in "$SCRIPTPATH/../doc/diagrams/"*.d2; do
  d2_filename=$(basename "$d2_file")
  svg_filename="${d2_filename%.d2}.svg"
	d2 "$d2_file" "$SCRIPTPATH/../doc/tech-docs/source/images/$svg_filename"
done