#!/bin/bash

if [ $# -eq 0 ]; then
	echo "Usage: $0 <project-directory>"
	exit 1
fi

PROJECT=$1

# Run from the base directory
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

# Create SVGs for all d2 diagrams in the project
while IFS= read -r -d '' d2_file; do
	diagram=$(basename "$d2_file")
	svg=${diagram%.d2}.svg
	d2 -t 8 --layout elk --pad 25 \
		"$SCRIPTPATH/../projects/${PROJECT}/tech-docs/diag/$diagram" \
		"$SCRIPTPATH/../projects/${PROJECT}/tech-docs/source/img/$svg"
done < <(
	find "$SCRIPTPATH/../projects/${PROJECT}/tech-docs/diag/" -iname "*.d2" -print0
)
