# Court Case Workflow: Case Note Published

direction: right

style { ...@../../../../script/style.style }
vars { ...@../../../../script/style.vars }
** { ...@../../../../script/style.all-style }

# What triggers the workflow?
case-notes-published: Court Case Note Published {
     style.font-size: 24

     explanation: |md
     ## Court Case Note Published
     - A Court case note is\
       published
     |

     case_note_published: Court Case Note Published
}

domain_event: "court-case-and-delius\n.court-case.comment.published" {
    style.font-size: 12
    shape: queue
}

# What happens in Delius?
delius: Delius {
    style.font-size: 24
    grid-columns: 2

    d_check_date: Check date of note
    d_merge_notes: Add/Merge case note

    d_check_date -> d_merge_notes

    explanation: |md
    ## Merge case notes
    - Check whether the notes have\
      arrived out of order. If so,\
      log a warning and ignore notes
    - If case notes exist, merge the\
      case notes
    - Otherwise, add new case notes
    |

}

case-notes-published -> domain_event -> delius
