openapi: 3.0.1
info:
  title: API Reference
  contact:
    name: Probation Integration Team
    url: https://mojdt.slack.com/archives/C02HQ4M2YQN
    email: probation-integration-team@digital.justice.gov.uk
  license:
    name: MIT
    url: https://github.com/ministryofjustice/hmpps-probation-integration-services/blob/main/LICENSE
  version: "1.0"
servers:
- url: /
security:
- hmpps-auth-token: []
paths:
  /person/populate-noms-number:
    get:
      tags:
      - matching-controller
      operationId: populateNomsNumbers
      parameters:
      - name: dryRun
        in: query
        required: false
        schema:
          type: boolean
          default: true
      - name: crns
        in: query
        required: false
        schema:
          maxItems: 500
          minItems: 1
          type: array
          items:
            type: string
      responses:
        "200":
          description: OK
    post:
      tags:
      - matching-controller
      operationId: populateNomsNumbers_1
      parameters:
      - name: dryRun
        in: query
        required: false
        schema:
          type: boolean
          default: true
      requestBody:
        content:
          application/json:
            schema:
              maxItems: 500
              minItems: 1
              type: array
              items:
                type: string
      responses:
        "200":
          description: OK
components:
  securitySchemes:
    hmpps-auth-token:
      type: http
      name: Authorization
      in: header
      scheme: bearer
      bearerFormat: JWT
