# Risk Assessment Workflow: Risk Assessment Submitted

direction: right

style { ...@../../../../script/style.style }
vars { ...@../../../../script/style.vars }
** { ...@../../../../script/style.all-style }

# What triggers the workflow?
assessment-submitted: Risk Assessment Submitted {
     style.font-size: 24

     explanation: |md
     ## Risk Assessment Submitted
     - A risk assessment is\
       produced in OASys
     |

     risk_assessment_produced: Risk Assessment Submitted
}

domain_event: "risk-assessment\n.scores.ogrs.determined" {
    style.font-size: 12
    shape: queue
}

# What happens in Delius?
delius: Delius {
    style.font-size: 24
    grid-columns: 2

    d_store_scores: Add/Update risk assessment scores
    d_contact: Create Contact
    d_create_mte: Create management tier event

    d_store_scores -> d_contact -> d_create_mte

    explanation: |md
    ## Risk Assessment Submitted
    - Check for an existing\
      risk assessment
    - Add/Update the risk\
      assessment scores
    - Create a new contact
    - Create a new management\
      tier event
    |

}

assessment-submitted -> domain_event -> delius
