# Risk Scores Workflow: Risk Scores Updated

direction: right

style { ...@../../../../script/style.style }
vars { ...@../../../../script/style.vars }
** { ...@../../../../script/style.all-style }

# What triggers the workflow?
risk-scores: Risk Scores Updated {
     style.font-size: 24

     explanation: |md
     ## Risk Scores Updated
     - RSR and OSP scores are\
       updated in the OASys system
     |

     risk_scores_updated: Risk Scores Updated
}

domain_event: "risk-assessment\n.scores.rsr.determined" {
    style.font-size: 12
    shape: queue
}

# What happens in Delius?
delius: Delius {
    style.font-size: 24

    explanation: |md
    ## Update Risk Scores 
    - Update the risk/
      scores in Delius
    |

}

risk-scores -> domain_event -> delius
