
style { ...@../../../../script/style.style }
vars { ...@../../../../script/style.vars }
** { ...@../../../../script/style.all-style }

context-oasys: OASys Context {
  entities: Entities {
    grid-columns: 3
    pop: Person on Probation
    rsr: RSR
    osp: OSP
    ogrs: OGRS score
    date: Assessment date
    event: Event number
  }
}

context-delius: Delius Context {

  interface: Risk Assessment\n and Delius {
    type: Anti-Corruption\nLayer
  }

  entities: Entities {
    grid-columns: 2
    event: Event
    mte: Management tier event
    contact: Contact
    pop: Person on Probation
    pm: Person manager
    staff: Staff
    team: Team
    ogrs-assessment: OGRS Assessment
  }
}

context-oasys--context-delius.interface: Upstream\n\n\nDownstream
