name: Report to S3
description: Publish results of an Azure Monitor Application Insights query to S3

inputs:
  query:
    description: Kusto query to run against Application Insights
    required: true
  role-arn:
    description: AWS Role ARN
    required: true
  bucket-name:
    description: S3 Bucket Name
    required: true
  bucket-prefix:
    description: S3 Bucket Object Prefix
    required: true
  azure_app_id:
    description: Azure Application Insights API Application ID
    required: true
  azure_client_id:
    description: Azure Client ID
    required: true
  azure_tenant_id:
    description: Azure Tenant ID
    required: true
  azure_subscription_id:
    description: Azure Subscription ID
    required: true

runs:
  using: "composite"
  steps:
    - name: Authenticate with AWS
      uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
      with:
        aws-region: eu-west-2
        role-to-assume: ${{ inputs.role-arn }}
        role-session-name: probation-integration-s3-export-${{ github.run_number }}
        role-duration-seconds: 1200

    - name: Authenticate with Azure
      uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}

    - name: Search Application Insights
      uses: azure/cli@9eb25b8360668fb0ecbafa808d40e2197b2f5f52
      id: search
      with:
        inlineScript: |
          token=$(az account get-access-token --resource https://api.applicationinsights.io --query accessToken -o tsv)
          curl -fsSL -H "Authorization: Bearer $token" --data-urlencode "query=$query" --get "$url" > result.json
      env:
        url: https://api.applicationinsights.io/v1/apps/${{ inputs.azure_app_id }}/query
        query: ${{ inputs.query }}

    - name: Export to S3
      shell: bash # language=bash
      run: |
        jq -rc '.tables[0] | (.columns | map(.name)) as $cols | .rows[] | with_entries(.key |= $cols[.])' result.json \
          | aws s3 cp - "s3://$bucket_name/$bucket_prefix" --acl bucket-owner-full-control --sse AES256
      env:
        bucket_name: ${{ inputs.bucket-name }}
        bucket_prefix: ${{ inputs.bucket-prefix }}
