package uk.gov.justice.digital.hmpps.api.model.contact

import java.time.LocalDate
import java.time.LocalTime

data class CreateContact(
    val date: LocalDate,
    val time: LocalTime,
    val staffCode: String,
    val teamCode: String,
    val type: String,
    val eventId: Long? = null,
    val requirementId: Long? = null,
    val description: String? = null,
    val notes: String? = null,
    val alert: Boolean = false,
    val sensitive: Boolean = false,
    val visorReport: Boolean = false
) {
    enum class Type(val code: String) {
        EmailTextFromOther("CM3A"),
        EmailTextFromPoP("CMOA"),
        EmailTextToOther("CM3B"),
        EmailTextToPoP("CMOB"),
        InternalCommunications("C326"),
        PhoneContactFromOther("CT3A"),
        PhoneContactFromPoP("CTOA"),
        PhoneContactToOther("CT3B"),
        PhoneContactToPoP("CTOB"),
        PoliceLiaison("C204"),
        AccommodationEvidence("ACOM1"),
        AssistanceAtCourtCourtQuery("CRTUP4"),
        AssistanceToCourtUpdateFromPP("CRTUP"),
        CaseConference("CCON"),
        CaseConsultation("RRPCC1"),
        CaseDiscussion("C238"),
        CaseReviewedByCaseManager("CRCO"),
        CMSAssistanceWithAssessments("CMS40"),
        CMSAssistanceWithCaseConferencing("CMS41"),
        CMSAttendingPartnershipMeetings("CMS42"),
        CMSCaseRelatedCommunication("CMS43"),
        CMSCompletingAndAssistingWithReferrals("CMS44"),
        CMSCourtLiaisonAndApplicationsToCourt("CMS45"),
        CMSHomeAndPrisonVisits("CMS47"),
        CMSInformationAndIntelligenceGathering("CMS48"),
        CMSROTLAssessmentsAndSupport("CMS49"),
        CMSSentencePlanInterventionDelivery("CMS50"),
        Comment("C201"),
        ConsultationWithManager("CSPO"),
        ContactWithElectronicMonitoringProvider("C063"),
        CoreGroupMeeting("NSD1"),
        CPSReceived("C016"),
        GangMemberInformationSharing("C344"),
        HDCCorrespondenceCommunication("CDHC"),
        HealthAndSocialServiceLiaison("C203"),
        HealthAndWellBeingReferral("C115"),
        InformationFrom3rdParty("CI3A"),
        InformationFromEMSProvider("INFFES"),
        InformationFromExternalAgency("CIEA"),
        InformationFromPoP("CIOA"),
        InformationOther("CIZZ"),
        InformationTo3rdParty("CI3B"),
        InformationToEMSProvider("INFTES"),
        InformationToExternalAgency("CIEB"),
        InformationToPoP("CIOB"),
        InformationDocumentsRequested("C325"),
        InformationFromCourtTeam("C294"),
        InterpreterRequestedConfirmed("C333"),
        IOMCaseConference("ICON"),
        IOMCorrespondenceMailContact("CAIL"),
        IOMReview("CAIR"),
        LetterFaxFromOther("CL3A"),
        LetterFaxFromPoP("CLOA"),
        LetterFaxToOther("CL3B"),
        LetterFaxToPoP("CLOB"),
        LiaisonWithDrugTreatmentProvider("CLDR"),
        LicenceComplianceLetter("LCL"),
        LiferReviewPanel("LRP1"),
        MAPPAInformation("C200"),
        MAPPAJFormJobCentreNotification("C484"),
        MAPPALevelSettingProcess("MAPLS"),
        MAPPAMeeting("CCMM"),
        MARACPerpetratedDVIncident("C150"),
        MARACVictimOfDVIncident("C151"),
        MaracMeeting("C005"),
        OrderLicenceReceived("C256"),
        OtherEnforcementAction("BRED"),
        ParoleHearingNotificationOfOutcome("C395"),
        POMCOMStandardHandoverInformationReceived("POM4"),
        PreConsRequested("C187"),
        PreventActivity("PREVENT"),
        PrisonLiaison("C202"),
        QAHDC2And3PD1Received("C399"),
        QAHDC3PD1ReturnedToPrison("C401"),
        RequestForInformation("CRFI"),
        RiskNotificationToEMSProvider("RTEMS"),
        ROTLRelease("ROTL"),
        ROTLReturn("ROTR"),
        SafeguardingChildProtectionCoreGroupMeeting("C159"),
        SafeguardingChildProtectionMeeting("C078"),
        SafeguardingChildRelatedContact("C157"),
        SafeguardingVulnerableAdultContact("C161"),
        SafeguardingVulnerableAdultStrategyMeeting("C160"),
        SafeguardingAssessment("EASS"),
        SafeguardingCaseConference("CCCP"),
        SensitiveInformationContact("CNDC"),
        SickNoteReceived("CSNR"),
        SubstanceUseScreeningTool("DRAT"),
        SuicideSelfHarmInformation("C280"),
        TextMessageToSend("CTXT"),
        UseOfVideoLinkTeleconference("C129"),
        VictimLiaisonContact("CVIC"),
        ViSORInformationContact("VINC")
    }
}
