database:
  access:
    username_key: /single-accommodation-and-delius/db-username
    password_key: /single-accommodation-and-delius/db-password

  audit:
    username: SingleAccommodationAndDelius
    forename: Single Accommodation
    surname: Service
