
style { ...@../../../../script/style.style }
vars { ...@../../../../script/style.vars }
** { ...@../../../../script/style.all-style }

context-hmpps: HMPPS Context {

  entities: Entities {
    grid-columns: 2
    user: User
    role: Role
    authentication: Authentication
  }
}

context-delius: Delius Context {

  interface: HMPPS and\n Delius {
    type: Anti-Corruption\nLayer
  }

  entities: Entities {
    grid-columns: 2
    user: User
    scope: Scope
    role: Role
    role-association: Role association
    authentication: Authentication
  }
}

context-hmpps--context-delius.interface: Upstream\n\n\nDownstream
