# Resettlement Passport Workflow: Create Appointment

direction: right

style { ...@../../../../script/style.style }
vars { ...@../../../../script/style.vars }
** { ...@../../../../script/style.all-style }

# What triggers the workflow?
resettlement-passport: Resettlement Passport {
     style.font-size: 24

     explanation: |md
     ## Appointment Workflow
     Resettlement activity results in an appointment
     |
}

# What happens in Delius?
delius: Delius {
    style.font-size: 24

     explanation: |md
     ## Appointment Workflow
     Appointment contacts are added to Delius\
     for each appointment
     |

    d_contact: Create Contact
}

resettlement-passport --> delius: HTTP POST
