openapi: 3.0.1
info:
  title: API Reference
  contact:
    name: Probation Integration Team
    url: https://mojdt.slack.com/archives/C02HQ4M2YQN
    email: probation-integration-team@digital.justice.gov.uk
  license:
    name: MIT
    url: https://github.com/ministryofjustice/hmpps-probation-integration-services/blob/main/LICENSE
  version: "1.0"
servers:
- url: /
security:
- hmpps-auth-token: []
paths:
  /overview/{crn}:
    get:
      tags:
      - Overview
      summary: "MAS Overview containing Personal Details, Activity, Compliance, Schedule,\
        \ Orders and Sentences "
      operationId: getOverview
      parameters:
      - name: crn
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Overview'
components:
  schemas:
    Activity:
      required:
      - acceptableAbsences
      - complied
      - nationalStandardsAppointments
      - rescheduled
      type: object
      properties:
        acceptableAbsences:
          type: integer
          format: int32
        complied:
          type: integer
          format: int32
        nationalStandardsAppointments:
          type: integer
          format: int32
        rescheduled:
          type: integer
          format: int32
    Compliance:
      required:
      - currentBreaches
      - failureToComplyInLast12Months
      type: object
      properties:
        currentBreaches:
          type: integer
          format: int32
        failureToComplyInLast12Months:
          type: integer
          format: int32
    Disability:
      required:
      - description
      type: object
      properties:
        description:
          type: string
    Name:
      required:
      - forename
      - surname
      type: object
      properties:
        forename:
          type: string
        middleName:
          type: string
        surname:
          type: string
    NextAppointment:
      required:
      - date
      - description
      type: object
      properties:
        date:
          type: string
          format: date-time
        description:
          type: string
    Offence:
      required:
      - code
      - description
      type: object
      properties:
        code:
          type: string
        description:
          type: string
    Order:
      required:
      - description
      - startDate
      type: object
      properties:
        description:
          type: string
        endDate:
          type: string
          format: date
        startDate:
          type: string
          format: date
    Overview:
      required:
      - personalDetails
      - previousOrders
      - schedule
      - sentences
      type: object
      properties:
        activity:
          $ref: '#/components/schemas/Activity'
        compliance:
          $ref: '#/components/schemas/Compliance'
        personalDetails:
          $ref: '#/components/schemas/PersonalDetails'
        previousOrders:
          $ref: '#/components/schemas/PreviousOrders'
        schedule:
          $ref: '#/components/schemas/Schedule'
        sentences:
          type: array
          items:
            $ref: '#/components/schemas/Sentence'
    PersonalCircumstance:
      required:
      - subType
      - type
      type: object
      properties:
        subType:
          type: string
        type:
          type: string
    PersonalDetails:
      required:
      - disabilities
      - name
      - personalCircumstances
      - preferredGender
      - provisions
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
        preferredGender:
          type: string
        preferredName:
          type: string
        telephoneNumber:
          type: string
        mobileNumber:
          type: string
        disabilities:
          type: array
          items:
            $ref: '#/components/schemas/Disability'
        provisions:
          type: array
          items:
            $ref: '#/components/schemas/Provision'
        personalCircumstances:
          type: array
          items:
            $ref: '#/components/schemas/PersonalCircumstance'
    PreviousOrders:
      required:
      - breaches
      - count
      type: object
      properties:
        breaches:
          type: integer
          format: int32
        count:
          type: integer
          format: int32
    Provision:
      required:
      - description
      type: object
      properties:
        description:
          type: string
    Rar:
      required:
      - completed
      - scheduled
      - totalDays
      type: object
      properties:
        completed:
          type: integer
          format: int32
        scheduled:
          type: integer
          format: int32
        totalDays:
          type: integer
          format: int32
    Schedule:
      type: object
      properties:
        nextAppointment:
          $ref: '#/components/schemas/NextAppointment'
    Sentence:
      required:
      - additionalOffences
      - mainOffence
      type: object
      properties:
        additionalOffences:
          type: array
          items:
            $ref: '#/components/schemas/Offence'
        mainOffence:
          $ref: '#/components/schemas/Offence'
        order:
          $ref: '#/components/schemas/Order'
        rar:
          $ref: '#/components/schemas/Rar'
  securitySchemes:
    hmpps-auth-token:
      type: http
      name: Authorization
      in: header
      scheme: bearer
      bearerFormat: JWT
