database:
  access:
    username_key: /manage-supervision-and-delius/db-username
    password_key: /manage-supervision-and-delius/db-password
    tables:
      - contact
      - contact_alert
      - offender
      - offender_address
      - audited_interaction
      - document
      - enforcement
      - r_enf_act_contact_out_type

  audit:
    username: ManageSupervisionAndDelius
    forename: Manage People on Probation
    surname: Service
