name: Diagrams

on:
  push:
    paths:
      - 'doc/diagrams/*.d2'

jobs:
  generate:
    name: Generate diagrams
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Install D2
        run: |
          curl -fsSLO "https://github.com/terrastruct/d2/releases/download/$VERSION/d2-$VERSION-$OS-$ARCH.tar.gz"
          tar -xzf "d2-$VERSION-$OS-$ARCH.tar.gz"
          make -sC "d2-$VERSION" install
        env:
          VERSION: v0.7.0
          OS: linux
          ARCH: amd64

      - name: Generate images
        run: |
          ./script/generate-diagrams
          git add doc/tech-docs/source/images

      - name: Commit and push
        uses: grafana/github-api-commit-action@b1d81091e8480dd11fcea8bc1f0ab977a0376ca5 # v1.0.0
        with:
          success-if-no-changes: true
          commit-message: Generate images from diagrams
          token: ${{ steps.app-token.outputs.token }}
