name: Diagrams

on:
  push:
    paths:
      - 'doc/diagrams/*.d2'

jobs:
  generate:
    name: Generate diagrams
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Install D2
        run: |
          curl -fsSLO "https://github.com/terrastruct/d2/releases/download/$VERSION/d2-$VERSION-$OS-$ARCH.tar.gz"
          tar -xzf "d2-$VERSION-$OS-$ARCH.tar.gz"
          make -sC "d2-$VERSION" install
        env:
          VERSION: v0.7.0
          OS: linux
          ARCH: amd64

      - name: Generate images
        run: |
          ./script/generate-diagrams
          git add doc/tech-docs/source/images

      - name: Commit and push
        uses: grafana/github-api-commit-action@b1d81091e8480dd11fcea8bc1f0ab977a0376ca5 # v1.0.0
        with:
          success-if-no-changes: true
          commit-message: Generate images from diagrams
          token: ${{ steps.app-token.outputs.token }}
