name: Security

on:
  schedule:
    - cron: "30 5 * * MON-FRI" # Every weekday at 05:30 UTC
  workflow_dispatch:

jobs:
  get-projects:
    permissions:
      contents: read
    uses: ./.github/workflows/get-projects.yml
    with:
      projects: All

  veracode-scan:
    permissions:
      contents: read
      checks: write
      id-token: write
      issues: write
      security-events: write
    runs-on: ubuntu-latest
    needs:
      - get-projects
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-gradle
        with:
          cache-role: ${{ secrets.GRADLE_CACHE_S3_ROLE_TO_ASSUME }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build jars
        run: ./gradlew jar

      - name: Package jars
        run: find . -name '*.jar' | zip -r package.zip -@

      - name: Select an API key
        run: |
          echo "Randomly picking 1 of 5 api keys, to help avoid veracode API rate limits."
          X=$(( RANDOM % 5 ))
          VERACODE_API_ID_X="VERACODE_API_ID_${X}"
          VERACODE_API_KEY_X="VERACODE_API_KEY_${X}"
          echo VERACODE_API_ID="${!VERACODE_API_ID_X}" >> $GITHUB_ENV
          echo VERACODE_API_KEY="${!VERACODE_API_KEY_X}" >> $GITHUB_ENV
          echo "Using VERACODE_API_ID_${X} from pool (${VERACODE_API_ID:0:5}...)"
        env:
          VERACODE_API_ID_0: ${{ secrets.HMPPS_VERACODE_API_ID_0 }}
          VERACODE_API_ID_1: ${{ secrets.HMPPS_VERACODE_API_ID_1 }}
          VERACODE_API_ID_2: ${{ secrets.HMPPS_VERACODE_API_ID_2 }}
          VERACODE_API_ID_3: ${{ secrets.HMPPS_VERACODE_API_ID_3 }}
          VERACODE_API_ID_4: ${{ secrets.HMPPS_VERACODE_API_ID_4 }}
          VERACODE_API_KEY_0: ${{ secrets.HMPPS_VERACODE_API_KEY_0 }}
          VERACODE_API_KEY_1: ${{ secrets.HMPPS_VERACODE_API_KEY_1 }}
          VERACODE_API_KEY_2: ${{ secrets.HMPPS_VERACODE_API_KEY_2 }}
          VERACODE_API_KEY_3: ${{ secrets.HMPPS_VERACODE_API_KEY_3 }}
          VERACODE_API_KEY_4: ${{ secrets.HMPPS_VERACODE_API_KEY_4 }}

      - name: Upload to Veracode
        uses: veracode/veracode-uploadandscan-action@0.2.11
        with:
          appname: hmpps-probation-integration-services
          createprofile: false
          deleteincompletescan: 2 # force delete any incomplete scans
          filepath: package.zip
          vid: ${{ env.VERACODE_API_ID }}
          vkey: ${{ env.VERACODE_API_KEY }}


