name: Test

on:
  schedule:
    - cron: "*/5 * * * MON"
  workflow_dispatch:

jobs:
  schedule-test:
    environment: azure-prod
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI Login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5
        with:
          subscription-id: ${{ secrets.APP_INSIGHTS_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.APP_INSIGHTS_TENANT_ID }}
          client-id: ${{ secrets.APP_INSIGHTS_CLIENT_ID }}
